namespace CompoundInterestCalculator.Application.Queries.CalculateCompoundInterest;

public interface ICalculateCompoundInterestQuery
{
    ICalculateCompoundInterestOutput Execute(ICalculateCompoundInterestInput input, CancellationToken cancellationToken);
}