using CompoundInterestCalculator.Domain.Models.CompoundInterestCalculator;

namespace CompoundInterestCalculator.Domain.Services.CalculateCompoundInterest;

public interface ICalculateCompoundInterestService
{
    ICompoundInterestCalculatorOutput Execute(ICompoundInterestCalculatorInput input, CancellationToken cancellationToken);
}